server:
  port: 9100 # 伺服器的port號

spring:
  h2:
    console:
      enabled: true
  datasource:
#    schema: src/resources/schema.sql
#    data: src/resources/data.sql
    url: jdbc:h2:mem:coin # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password: test123 # database 密碼


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true