INSERT INTO coin (ID, CODE, NAME, CREATE_TIME) VALUES (1, 'USD', '美元', CURRENT_TIMESTAMP);
INSERT INTO coin (ID, CODE, NAME, CREATE_TIME) VALUES (2, 'GBP', '英鎊', CURRENT_TIMESTAMP);
INSERT INTO coin (ID, CODE, NAME, CREATE_TIME) VALUES (3, 'EUR', '歐元', CURRENT_TIMESTAMP);