INSERT INTO coin (CODE, NAME, CREATE_TIME) VALUES ('USD', '美元', CURRENT_TIMESTAMP);
INSERT INTO coin (CODE, NAME, CREATE_TIME) VALUES ('GBP', '英鎊', CURRENT_TIMESTAMP);
INSERT INTO coin (CODE, NAME, CREATE_TIME) VALUES ('EUR', '歐元', CURRENT_TIMESTAMP);